# Pour le POC, on utilise une simple image Nginx pour servir des fichiers statiques
FROM nginx:alpine

# Définir le répertoire de travail
WORKDIR /usr/share/nginx/html

# (Plus tard, nous ajouterons ici les commandes de build React/Vue)
# COPY . .

EXPOSE 80
