"""has_phases sur Project, phase resp_suivi charges_hj sur Action, suppression priorite

Revision ID: 17abe753dbc6
Revises: 7bbe364cef5c
Create Date: 2026-08-07 02:11:05.233057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17abe753dbc6'
down_revision: Union[str, None] = '7bbe364cef5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actions', sa.Column('phase', sa.String(length=10), nullable=True))
    op.add_column('actions', sa.Column('charges_hj', sa.Float(), nullable=True))
    op.drop_column('actions', 'priorite')
    op.add_column('projects', sa.Column('has_phases', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'has_phases')
    op.add_column('actions', sa.Column('priorite', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('actions', 'charges_hj')
    op.drop_column('actions', 'phase')
    # ### end Alembic commands ###
