"""colonnes G-M sur Action: spi otd date_realisation priorite resp_suivi commentaire

Revision ID: 7bbe364cef5c
Revises: 
Create Date: 2026-08-06 19:04:20.545276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bbe364cef5c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actions', sa.Column('spi', sa.Float(), nullable=True))
    op.add_column('actions', sa.Column('otd', sa.Float(), nullable=True))
    op.add_column('actions', sa.Column('date_realisation', sa.Date(), nullable=True))
    op.add_column('actions', sa.Column('priorite', sa.String(length=50), nullable=True))
    op.add_column('actions', sa.Column('resp_suivi', sa.String(length=255), nullable=True))
    op.add_column('actions', sa.Column('commentaire', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('actions', 'commentaire')
    op.drop_column('actions', 'resp_suivi')
    op.drop_column('actions', 'priorite')
    op.drop_column('actions', 'date_realisation')
    op.drop_column('actions', 'otd')
    op.drop_column('actions', 'spi')
    # ### end Alembic commands ###
